### ISSUE TITLE
V3 API: Unable to grab Name on Account for checking accounts

### ISSUE THREAD

**Issue by BenGoldberg** [recurly/recurly-client-dotnet#448]
WIth the v2 library, it was possible to grab the name on account for a checking account when grabbing the billing information. However with the new v3 library, I no longer see a way of grabbing the name on account. Is it possible to have this information returned through the library?

**Comment by BenGoldberg** [comment]
Any comment on this? Now that V3 has officially been released we will look to deploy our changes, but this is the one breaking change from the V2 API for us.

**Comment by bhelx** [comment]
@BenGoldberg I can look at getting this added, if you have access to the account, name_on_account is a composition of first and last name: 

```ruby
[first_name.presence, last_name.presence].compact.join ' '
```

**Comment by bhelx** [comment]
@BenGoldberg are you blocked on it? is composing the name a valid workaround for your use case?

**Comment by bhelx** [comment]
You should be able to find this on the BillingInfo.PaymentMethod object:
https://github.com/recurly/recurly-client-dotnet/blob/8bcdfa70543ed1f2ff0816509d638537f73d15b4/Recurly/Resources/BillingInfo.cs#L56
https://github.com/recurly/recurly-client-dotnet/blob/8bcdfa70543ed1f2ff0816509d638537f73d15b4/Recurly/Resources/PaymentMethod.cs#L60
