### ISSUE TITLE
Missing gift card support in V3?

### ISSUE THREAD

**Issue by tcmorris** [recurly/recurly-client-dotnet#488]
It looks like the ability to create gift cards and go through that process is missing from the V3 version of the API?

Looking here all the API docs link to V2:
https://docs.recurly.com/docs/gift-cards#section-api

The only reference to gift cards in V3 was the option to include the redemption code during a purchase. `gift_card_redemption_code`

Could you advise if this is supported or not?

**Comment by douglasmiller** [comment]
Hi @tcmorris, thank you for your question. The v3 API does not currently include support for gift cards. We will look into the requirements to add support for that feature.

In the interim, you can use both v2 and v3 clients in conjunction if you prefer the features of v3 but need access to the gift card features.

**Comment by tcmorris** [comment]
Ok thanks for the update @douglasmiller.

It is a little disappointing that you would release a new version of the API without the functionality of the previous whilst still advertising the feature on the main website for Recurly. It would be handy to specify within the docs as a V2 only feature if that is the case.

Will look into this workaround for now.

**Comment by bhelx** [comment]
@tcmorris This work is being planned but not by our team. If you're interested in getting more information, I suggest reaching out to support. They may be able to get you early access and/or an ETA.
