### ISSUE TITLE
GiftCard Create doesn't return the response

### ISSUE THREAD

**Issue by tcmorris** [recurly/recurly-client-dotnet#507]
**Describe the bug**

The response from creating a gift card is not returned by the library. (v2)
https://dev.recurly.com/docs/create-gift-card

**To Reproduce**

Create new gift card object and call `Create()` method. The method return type is `void`, so the response from the API call isn't returned.

**Expected behavior**

Would expect the returned response from the API call. The gift card that was created or errors relating to why the gift card couldn't be created.

It looks like a few of the library methods have this issue. e.g. `Redeem()`

**Comment by douglasmiller** [comment]
Hello again, @tcmorris! The v2 client libraries are quite different in how they behave in comparison to the v3 clients. With the v2 client, the call to `Create()` will send the API request and populate any updated information on the object that you called `Create()` on. 

```csharp
var giftCard = new GiftCard("benjamin-du-monde", delivery, "test_gift_card", 1000, "USD");

try {
    giftCard.Create();
    System.Console.WriteLine("GiftCard created:" + giftCard.Id);
} catch (RecurlyException e) {
    // Error handling here
}
```

Any errors that occur will be thrown as a base type of [`RecurlyException`](https://github.com/recurly/recurly-client-dotnet/blob/v2/Library/Exception.cs), with several different variations.

**Comment by tcmorris** [comment]
Hello! Ah that makes more sense. Thanks for the explanation, must have missed that when reviewing the docs. Will close.
