### ISSUE TITLE
Adding an interface for the Client. V3

### ISSUE THREAD

**Issue by flyingtiger71** [recurly/recurly-client-dotnet#527]
There are a couple of nice advantages to having an interface exposed for the client and then have the client implement the interface. 
1. Allows for consumers to Mock the client for easy unit testing.
2. Allows for Dependency Injection.

**Comment by bhelx** [comment]
Hey @flyingtiger71 , thanks for the input. We've been asked this before. Since it's coming up a few times, we'll consider it. I'm going to leave this open for discussion.

In the mean time, I wanted to point out that we've had success mocking using the [moq](https://github.com/moq/moq4) library.

**Comment by bhelx** [comment]
As we discussed on the call, I'll generate the IClient interface alongside the client and make the client implement it. I'll be working on it this sprint.

**Comment by bhelx** [comment]
@flyingtiger71 would love to get your comments on #554 when you get the chance.
