### ISSUE TITLE
ListAccountSubscriptions returning expired subscriptions when specifying state="live"

### ISSUE THREAD

**Issue by BenGoldberg** [recurly/recurly-client-dotnet#531]
I recently upgraded the Recurly library to 3.6.1, we were using 3.0.0 before. After updating the library we noticed an issue that wasn't there before.

`_client.ListAccountSubscriptions($"code-{accountCode}", state: "live").ToList();`

This line was previously just returning the active subscriptions on an account, but now it's also returning expired subscriptions. I checked the documentation [here](https://developers.recurly.com/api/v2019-10-10/index.html#operation/list_account_subscriptions) and I believe this is incorrect. Specifically, the documentation specifies:

> When state=live, only subscriptions that are in an active, canceled, or future state or are in trial will be returned.

Has this functionality been changed and the documentation not updated or is this a problem specific with the new client?

**Comment by douglasmiller** [comment]
Thank you for reporting this issue, @BenGoldberg.

I was able to reproduce and have identified the issue. We will publish an updated client once the fix has been verified.

**Comment by BenGoldberg** [comment]
Thank you for the quick response! I look forward to the fix being released.

**Comment by douglasmiller** [comment]
@BenGoldberg I've created the referenced pull request to address the bug that you reported. There have been a lot of updates to the `Pager` class recently and it's a rather delicate beast. This bug fix is something that I've been trying to wrap my head around recently and couldn't quite connect all of the dots before.

Thanks again for taking the time to report this issue!

**Comment by douglasmiller** [comment]
@BenGoldberg the pull request just got merged and we will be releasing an updated client today. I'll keep you posted.

**Comment by BenGoldberg** [comment]
Is there an updated ETA for the release of this bug fix?

**Comment by bhelx** [comment]
Apologies @BenGoldberg, I believe it got held up for an unrelated reason. It'll be released after we merge #533
