### ISSUE TITLE
Proxy Calls to Third Party Like Card Easy V3

### ISSUE THREAD

**Issue by flyingtiger71** [recurly/recurly-client-dotnet#535]
Currently my company needs to be able to proxy calls to a third party vendor that handles credit card collection and storage.  We have implemented a solution in the V2 code where we set a proxy on the config settings.  Then if the proxy is set it is used when making the requests.

Code from V2 forked dll

new property on the Settings class
```
public string Proxy
        {
            get
            {
                if(_hasLoaded == false)
                {
                    throw new Exception("The Recurly client has no configuration initialized, please add your settings to web/app.config or call Recurly.Configuration.SettingsManager.Initialize(args)");
                }

                return _proxy;
            }
            private set { _proxy = value; }
        }
```

Modified GetServerURI
```
public string GetServerUri(string givenPath)
        {
            if (givenPath.Contains("://"))
                return givenPath;

            if(!string.IsNullOrWhiteSpace(Proxy))
            {
                return string.Format("{0}/v2{1}", Proxy, givenPath);
            }

            return string.Format(RecurlyServerUri, Subdomain, givenPath);
        }
```
Example recurly config setting with proxy
```
<recurly apiKey="000000000000000" subdomain="SomeSubDomain" pageSize="50" proxy="https://us-west.ceclients.syntec.co.uk/ceproxy/direct/55555/{SomeSubDomain}.recurly.com" />
```

We would like to have the same ability with V3
My initial thoughts were to add a constructor to the Client and have the base client use the proxy

**Comment by bhelx** [comment]
@flyingtiger71 there is a hidden method for doing this already. `Client._SetApiUrl`: https://github.com/recurly/recurly-client-dotnet/blob/master/Recurly/BaseClient.cs#L92

You need an env variable `RECURLY_INSECURE` set to `true` for this to work. Does this unblock you for the time being? I am still thinking about how best to support this in a secure manner.

**Comment by flyingtiger71** [comment]
@bhelx I think that might work.  This can be closed.

**Comment by bhelx** [comment]
Great! We're going to keep a ticket open in our system so we can look at officially supporting this though.
